### ISSUE TITLE
currency key error

### ISSUE THREAD

**Issue by lucamariotti** [Fuyucch1/Vinted-Notifications#10]
Hi, 
thank you for your amazing job.
I would like to ask you if you had a similar error related to 'currency'?
The bot was working until yesterday and in the logs I can see the following error.
![Capture](https://github.com/user-attachments/assets/e48a4f0c-0989-48ce-a8db-2f4b055f5a09)
the query used was the following: 

https://www.vinted.it/catalog?search_text=echo%20dot&search_id=18334468258&time=1730648152&order=newest_first&price_from=5&currency=EUR&price_to=25&page=1

Best, 
Luca

**Comment by Fuyucch1** [comment]
Hello there!

This is related to Vinted api's update that happened yesterday. Luckily, I caught the error as soon as it rolled out and did a [https://github.com/herissondev/vinted-api-wrapper/pull/21](PR) on pyVinted's library to fix it.

It's already deployed, just update your dependencies (pyVinted to 0.5.1) and the error will be fixed!

Have a nice day!

**Comment by lucamariotti** [comment]
Many thanks, it works :)
