### ISSUE TITLE
401 Client error

### ISSUE THREAD

**Issue by lucamariotti** [Fuyucch1/Vinted-Notifications#11]
Hi, I have this error below: 
![image](https://github.com/user-attachments/assets/00831d11-ffc3-42da-a85c-8c708e7da0e9)

Have you any idea behind this 401 error?
I'm using the latest version of the repo.
Best, 
Luca

**Comment by Fuyucch1** [comment]
Hello there!

I haven't met this one yet. Is the bot looping on the error or does it fix it by generating a new cookie ? (I'm wondering if it isn't just the cookie expiring)

**Comment by lucamariotti** [comment]
Hi, 
thank you for your answer, 
No is looping on the error. 
I have also remove the vinted.db and try to rerun the procedure by including new queries, but still the same error. 
Best,
Luca

**Comment by lucamariotti** [comment]
Hi, 
hope everything is going well, the issue is the same mentioned here: 
https://github.com/herissondev/vinted-api-wrapper/issues/22#issue-2675596696
Best, 
Luca

**Comment by Fuyucch1** [comment]
Hello there,
Sorry for the delay! I just came back from vacation.
I think the library's developer found what cause the issue and will fix it soon. Wait & see!

**Comment by Fuyucch1** [comment]
This should work now, I've updated the requirements file. Update your dependencies and tell me if it works!

**Comment by lucamariotti** [comment]
Hi, yes it works! thank you for your time and also to @herissondev to fix this.
