### ISSUE TITLE
Vinted gives unrelated listings

### ISSUE THREAD

**Issue by Fuyucch1** [Fuyucch1/Vinted-Notifications#2]
When looking for items, Vinted sometimes returns unrelated listings.

Should add a verificatio barrier such as

if keyword in title or description => notify
else pass

should be careful around keywords composed of multiple words though

**Comment by Fuyucch1** [comment]
1. There's no description in the items
2. Sometime items are sent because the keyword is in the member name
=> Should I forbid this ? I don't think so.
3. For some items... I don't know how Vinted returned those. I just don't know.

**Comment by Fuyucch1** [comment]
actually, there's no description in the items... in the catalog/items endpoing

if you go into the user/items endpoint, you can find the description there 

```api/user/[user_id]/items?selected_item_id=[item_id]```
![image](https://github.com/user-attachments/assets/7bfb0268-adcd-47d2-a8bf-2d895af1492a)

**Comment by herissondev** [comment]
I would recommend you not searching based on keywords but rather catalog_ids/brand_id.. (+ keyword if needed), this erases a lot of false positives when searching for a specific item.

**Comment by Fuyucch1** [comment]
> I would recommend you not searching based on keywords but rather catalog_ids/brand_id.. (+ keyword if needed), this erases a lot of false positives when searching for a specific item.

Thanks for the suggestion! However, my use case is a bit specific.. I am searching for books, so there are (almost) never any brands mentioned in the listings. 

I hadn't thought of sorting by brand though. If I exclude branded listings, I'll be fine with my books, but that makes the tool less versatile.

Since I always grab the user_country (to avoid getting books in a foreign language), the api also returns the item_description. Isn't checking if (title+description) contains the keywords worth a try to avoid false positives?

**Comment by herissondev** [comment]
You also have a cataog_id parameter that lets you search for a particular type of items. For examples books have a catalog id of 2312 (`catalog[]=2312`). Add this to your search query and you will only get books! 

> Since I always grab the user_country (to avoid getting books in a foreign language), the api also returns the item_description. Isn't checking if (title+description) contains the keywords worth a try to avoid false positives?

This depends on your requirements, in my old projects I had to do so many requests that I could not allow for other "unnecessary" requests. But if your requirement is to be sure (and not fast) then yes you can.
But given that you only have books now thanks to catalog_id, it should be rare to have a book titled as the book you are searching for but not be it...
